### ISSUE TITLE
Diagrama de clases. METZTLI

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-Ferch0419#1]
[Diagrama de clases Metztli.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-Ferch0419/files/8453899/Diagrama.de.clases.Metztli.pdf)

**Comment by Yabin-2021** [comment]
Bien  hecho 

20 %

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/164063189-18542734-ebc7-4f30-bd6f-003af7ac95f8.png)
En programacion en Assembly no se utiliza herencia si es lo que estan tratando de ejemplificar en este diagrama

**Comment by josealfredo79** [comment]
Solo corregirlo para poder tomar en cuenta.

**Comment by Ferch0419** [comment]
Diagrama de clases Metztli ACTUALIZADO.

[Diagrama de clases Metztli.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-Ferch0419/files/8566740/Diagrama.de.clases.Metztli.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
